services:
  mysql:
    image: mysql:8
    container_name: shared-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: htt
      MYSQL_USER: share
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  mongo:
    image: mongo:6.0
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: htt-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
      - mongo
    networks:
      - mynetwork

volumes:
  mysql_data:
  mongo_data:

networks:
  mynetwork:
