services:

  mongo:
    image: mongo:6.0
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork:
