services:
  - type: web
    name: here-to-translate-frontend
    env: static
    region: singapore
    branch: main
    autoDeploy: true
    buildCommand: npm ci && npx nx build @here-to-translate/web
    staticPublishPath: ./apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-api-url.com/api
      - key: VITE_SERVER_URL
        value: https://your-backend-api-url.com
