services:
  - type: web
    name: here-to-translate-frontend
    env: static
    region: singapore
    branch: main
    autoDeploy: true
    buildCommand: npm install && ./node_modules/.bin/nx build @here-to-translate/common && ./node_modules/.bin/nx build @here-to-translate/web
    staticPublishPath: ./apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://htt-ekpa.onrender.com/api
      - key: VITE_SERVER_URL
        value: https://htt-ekpa.onrender.com
